cytn_core_homepage:
    path:     /
    defaults: { _controller: CYTNCoreBundle:Default:index }

cytn_core_addDeal:
    path: /addDeal
    defaults: { _controller: CYTNCoreBundle:Default:addDeal }

cytn_core_classification:
    path:     /classement
    defaults: { _controller: CYTNCoreBundle:Default:classification }