<?php

namespace CYTN\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * DealsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealsRepository extends EntityRepository
{
    public function getUserPts($userId)
    {
        $qb = $this->createQueryBuilder('d')
            ->addSelect('SUM(d.points) as pts')
            ->where('d.user = :id')
            ->setParameter('id', $userId)
            ->groupBy('d.user')
            //->orderBy('SUM(d.points)', 'desc')
        ;
        $resultat = $qb->getQuery()->getResult();

        return is_null($resultat[0]['pts']) ? 0 : $resultat[0]['pts'];
    }
}
