<?php

namespace CYTN\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupTeamRepository extends EntityRepository
{
}
