<?php

namespace CYTN\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends EntityRepository
{

    public function findByRound($round)
    {
        $query = $this->_em->createQuery('SELECT a FROM Groups a WHERE a.round = :round');
        $query->setParameter('round', $round);

        return $query->getResult();
    }

}
