<?php

namespace CYTN\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchTeamInRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchTeamInRepository extends EntityRepository
{
}
