<?php

namespace CYTN\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MatchsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
**/
class MatchsRepository extends EntityRepository
{
    public function findAllOpen()
    {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.startDate > :start')
            ->setParameter('start', new \DateTime())
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
